[package]
name = "examples-execd"
version = "0.0.0"
edition = "2021"
rust-version = "1.60"
publish = false

[dependencies]
libcnb = { path = "../../libcnb" }
fastrand = "1.7.0"

[dev-dependencies]
libcnb-test = { path = "../../libcnb-test" }
