api = "0.8"

[buildpack]
id = "libcnb-examples/ruby"
version = "0.1.0"
name = "Example libcnb buildpack: ruby"

[[stacks]]
id = "heroku-20"

[metadata]
ruby_url = "https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-20/ruby-2.7.4.tgz"
