[package]
name = "examples-ruby-sample"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
flate2 = { version = "1.0.26", default-features = false, features = ["zlib"] }
libcnb.workspace = true
serde = "1.0.166"
sha2 = "0.10.7"
tar = "0.4.38"
tempfile = "3.6.0"
ureq = "2.7.1"

[dev-dependencies]
libcnb-test.workspace = true
